[package]
name = "rustic-ink"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
axum = "0.6.18"
clap = { version = "4.3.1", features = ["derive"] }
hotwatch = "0.5.0"
pulldown-cmark = "0.9.3"
tokio = { version =  "1.28.2", features = ["full"] }
tower-http = { version = "0.4.0", features = ["fs", "trace"] }
walkdir = "2.3.3"
