[package]
name = "rustic-ink"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
axum = "0.6.18"
clap = { version = "4.3.1", features = ["derive"] }
config = "0.13.3"
env_logger = "0.10.0"
fs_extra = "1.3.0"
handlebars = "4.3.7"
hotwatch = "0.5.0"
log = "0.4.18"
pulldown-cmark = "0.9.3"
serde = "1.0.163"
serde_json = "1.0.96"
slugify = "0.1.0"
tokio = { version =  "1.28.2", features = ["full"] }
tower-http = { version = "0.4.0", features = ["fs", "trace"] }
walkdir = "2.3.3"
