[dev]
port = 3000

[site]
script_urls = []
style_urls = [
  'https://cdn.jsdelivr.net/npm/@picocss/pico@1/css/pico.min.css',
  'https://fonts.googleapis.com/css2?family=Fira+Sans:wght@300;400;700&display=swap',
]

[meta]
title = "~/Rusty!nk"
description = "Blazing fast static site generator written in Rust"
og_image_url = "https://rustyink.cli.rs/images/og.png"
base_url = "https://rustyink.cli.rs"

[navigation]
links = [
    { label = "~/", url = "/" },
    { label = "GitHub", url = "https://github.com/arjunkomath/rustyink" },
    { label = "Twitter", url = "https://twitter.com/arjunz" },
    { label = "Blog", url = "/blog/" },
    { label = "About", url = "/about/" },
]
