[dev]
port = 3000

[site]
code_highlighting = true
sitemap_base_url = "https://rustyink.cli.rs"

[meta]
title = "~/Rusty!nk"
description = "Blazing fast static site generator written in Rust"
og_image_url = "https://rustyink.cli.rs/images/og.png"

[navigation]
links = [
    { label = "~/", url = "/" },
    { label = "GitHub", url = "https://github.com/arjunkomath/rustyink" },
    { label = "Twitter", url = "https://twitter.com/arjunz" },
    { label = "Blog", url = "/blog" },
    { label = "About", url = "/about" },
]
