[dev]
port = 3000
ws_port = 3001

[site]
script_urls = []
style_urls = [
  'https://cdn.jsdelivr.net/npm/@picocss/pico@1/css/pico.min.css',
  'https://cdn.jsdelivr.net/npm/prismjs@1.29.0/themes/prism-tomorrow.min.css',
]

[meta]
title = "~/RustyInk"
description = "Blazing fast static site generator written in Rust"
og_image_url = "https://rustyink.cli.rs/images/og.png"
base_url = "https://rustyink.cli.rs"

[navigation]
links = [
  { label = "~/", url = "/" },
  { label = "GitHub", url = "https://github.com/arjunkomath/rustyink" },
  { label = "Twitter", url = "https://twitter.com/arjunz" },
  { label = "Blog", url = "/blog/" },
  { label = "About", url = "/about/" },
]

[data]
author = "Arjun Komath"
author_link = "https://twitter.com/arjunz"
