[dev]
port = 3000

[site]
code_highlighting = true

[meta]
title = "Rustic Ink"
description = "Blazing fast static site generator written in Rust"

[navigation]
links = [
    { label = "~/", url = "/" },
    { label = "GitHub", url = "https://github.com/arjunkomath/rustic-ink" },
    { label = "Twitter", url = "https://twitter.com/arjunz" },
]
